# Builds tickets.json from fetch.sh's downloads, prints statistics per tracker and every mention of AI or LLMs.
import json, glob, re, collections, datetime, html
rows = []
for tracker in ('bugs', 'feature-requests'):
    for f in glob.glob(f'{tracker}/*.json'):
        try:
            t = json.load(open(f))['ticket']
        except Exception as e:
            continue
        posts = [p for p in t['discussion_thread']['posts']]
        rows.append(dict(tracker=tracker, num=t['ticket_num'], date=t['created_date'][:10], status=t['status'],
            labels=t['labels'], reporter=t['reported_by'], summary=t['summary'], desc=t['description'],
            atts=[a['url'].rsplit('/',1)[-1] for a in t['attachments']] + [a['url'].rsplit('/',1)[-1] for p in posts for a in p.get('attachments',[])],
            posts=[(p['author'], p['timestamp'][:10], p['text']) for p in posts]))
json.dump(rows, open('tickets.json','w'))
print('tickets', len(rows))
for tracker in ('bugs','feature-requests'):
    rs = [r for r in rows if r['tracker']==tracker]
    print(f'\n== {tracker}: {len(rs)} tickets, {min(r["date"] for r in rs)} .. {max(r["date"] for r in rs)}')
    print(' status:', collections.Counter(r['status'] for r in rs).most_common())
    rep = collections.Counter(r['reporter'] for r in rs)
    print(' top reporters:', rep.most_common(8))
    auth = collections.Counter(a for r in rs for (a,_,txt) in r['posts'] if not txt.startswith('- **'))
    print(' top commenters:', auth.most_common(8))
    withpatch = [r for r in rs if any(re.search(r'\.(patch|diff|zip)$', a, re.I) for a in r['atts'])]
    print(f' with a patch/diff/zip attached: {len(withpatch)}; status:', collections.Counter(r['status'] for r in withpatch).most_common())
    nm = [r for r in rs if any(a=='nyamatongwe' for a,_,_ in r['posts'])]
    print(f' with a maintainer post: {len(nm)}')
# AI / LLM mentions
pat = re.compile(r'\b(LLM|LLMs|ChatGPT|Copilot|Claude|GPT-?\d|AI[- ]generated|AI assistant|generated by AI|artificial intelligence|language model)\b', re.I)
print('\n== AI / LLM mentions (ticket, author, date, excerpt)')
for r in sorted(rows, key=lambda r: r['date']):
    for where, a, d, txt in [('desc', r['reporter'], r['date'], r['desc'])] + [('post', a, d, txt) for a,d,txt in r['posts']]:
        m = pat.search(txt or '')
        if m:
            s = max(0, m.start()-120); print(f" {r['tracker'][:4]} #{r['num']} {d} {a} ({where}): ...{txt[s:m.end()+160]!r}")
